services:
  taskmanagementapi:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_started
    environment:
      POSTGRES_HOST: postgresql
    env_file:
      - .env
    networks:
      - default
    ports:
      - "8000:8000"

  postgresql:
    restart: always
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    name: ${IMAGE:-taskmanagementapi}

volumes:
  pgdata:
